/**
 * KodNest Premium Build System - Job Notification Tracker
 * Realistic Job Data Collection (60 entries)
 */

window.jobsData = [
    // 1-10: MNCs & Top Tech
    {
        id: 1,
        title: "SDE Intern",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹30k–₹50k/month",
        source: "LinkedIn",
        postedDaysAgo: 1,
        skills: ["Java", "Spring Boot", "MySQL", "Data Structures"],
        applyUrl: "https://www.phonepe.com/careers/",
        description: "Join our Payments Core team to build scalable transaction systems. You will work on high-volume distributed systems handling millions of transactions daily. Great opportunity for freshers with strong DSA skills."
    },
    {
        id: 2,
        title: "Frontend Engineer (React)",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "12–18 LPA",
        source: "Naukri",
        postedDaysAgo: 2,
        skills: ["React.js", "Redux", "TypeScript", "Tailwind CSS"],
        applyUrl: "https://careers.swiggy.com/",
        description: "Looking for a passionate Frontend Engineer to craft delightful user experiences for our consumer app. You should be proficient in React and modern CSS. Experience with performance optimization is a plus."
    },
    {
        id: 3,
        title: "Java Developer",
        company: "Infosys",
        location: "Pune",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "4–6 LPA",
        source: "Infosys Careers",
        postedDaysAgo: 3,
        skills: ["Core Java", "J2EE", "SQL", "HTML/CSS"],
        applyUrl: "https://www.infosys.com/careers/",
        description: "We are hiring entry-level Java developers for our digital transformation projects. Training will be provided. Candidates must have strong foundational knowledge in Java and good communication skills."
    },
    {
        id: 4,
        title: "Data Analyst Intern",
        company: "Cred",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹40k/month",
        source: "LinkedIn",
        postedDaysAgo: 0,
        skills: ["Python", "SQL", "Tableau", "Excel"],
        applyUrl: "https://cred.club/careers",
        description: "Work with our Analytics team to derive insights from user payment behavior. You will build dashboards and ad-hoc reports. proficiency in SQL and Python for data manipulation is required."
    },
    {
        id: 5,
        title: "Backend Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "8–12 LPA",
        source: "Zoho Careers",
        postedDaysAgo: 5,
        skills: ["Java", "PostgreSQL", "Redis", "Linux"],
        applyUrl: "https://www.zoho.com/careers/",
        description: "Join the team behind one of the world's most successful SaaS suites. We need backend developers who understand scale and security. Strong problem-solving skills are essential."
    },
    {
        id: 6,
        title: "System Engineer",
        company: "TCS",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "3.5–5 LPA",
        source: "TCS NextStep",
        postedDaysAgo: 1,
        skills: ["C++", "Python", "Computer Networks", "DBMS"],
        applyUrl: "https://www.tcs.com/careers",
        description: "TCS is hiring fresh graduates for the System Engineer role. You will work on enterprise-grade applications and IT infrastructure. Knowledge of cloud basics is an added advantage."
    },
    {
        id: 7,
        title: "Full Stack Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5 Years",
        salaryRange: "20–28 LPA",
        source: "LinkedIn",
        postedDaysAgo: 4,
        skills: ["Node.js", "React", "AWS", "MongoDB"],
        applyUrl: "https://razorpay.com/jobs/",
        description: "Help us revolutionize payments in India. We need full-stack engineers who can own features from database design to UI implementation. Experience with microservices architecture is preferred."
    },
    {
        id: 8,
        title: "DevOps Engineer",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "6–9 LPA",
        source: "Naukri",
        postedDaysAgo: 6,
        skills: ["Docker", "Kubernetes", "Jenkins", "Azure"],
        applyUrl: "https://careers.wipro.com/",
        description: "Looking for a DevOps engineer to manage our CI/CD pipelines and cloud infrastructure. Hands-on experience with Docker and Kubernetes is mandatory. Certification in Azure/AWS is a plus."
    },
    {
        id: 9,
        title: "Software Engineer - I",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "18–24 LPA",
        source: "LinkedIn",
        postedDaysAgo: 2,
        skills: ["Java", "Spring", "Kafka", "HBase"],
        applyUrl: "https://www.flipkartcareers.com/",
        description: "Join the Supply Chain Tech team at Flipkart. You will build high-availability systems that power India's e-commerce. Strong coding skills in Java and understanding of distributed systems required."
    },
    {
        id: 10,
        title: "Product Designer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "15–20 LPA",
        source: "LinkedIn",
        postedDaysAgo: 3,
        skills: ["Figma", "UI/UX", "Prototyping", "User Research"],
        applyUrl: "https://www.zomato.com/careers",
        description: "Design delightful food ordering experiences for millions of users. We are looking for designers with a strong portfolio and an eye for detail. Experience in consumer apps is preferred."
    },

    // 11-20: Startups & Mid-size
    {
        id: 11,
        title: "React Native Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "12–18 LPA",
        source: "Groww Careers",
        postedDaysAgo: 0,
        skills: ["React Native", "Redux", "Mobile App Dev", "JavaScript"],
        applyUrl: "https://groww.in/careers",
        description: "Build India's fastest-growing investment platform. We need React Native experts to ensure a smooth, native-like experience on both iOS and Android. Performance optimization skills are key."
    },
    {
        id: 12,
        title: "QA Engineer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "5–8 LPA",
        source: "Indeed",
        postedDaysAgo: 4,
        skills: ["Selenium", "Java", "TestNG", "Manual Testing"],
        applyUrl: "https://www.freshworks.com/company/careers/",
        description: "Ensure the quality of our SaaS products. You will write automated test scripts and perform manual testing. Knowledge of CI/CD integration for testing is desirable."
    },
    {
        id: 13,
        title: "Python Developer",
        company: "Accenture",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "7–11 LPA",
        source: "Naukri",
        postedDaysAgo: 1,
        skills: ["Python", "Django", "REST APIs", "PostgreSQL"],
        applyUrl: "https://www.accenture.com/in-en/careers",
        description: "Hiring Python developers for an international banking client project. You should be comfortable with Django/Flask and REST API development. Good communication skills are required."
    },
    {
        id: 14,
        title: "Machine Learning Intern",
        company: "InMobi",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹45k/month",
        source: "LinkedIn",
        postedDaysAgo: 2,
        skills: ["Python", "TensorFlow", "Pandas", "Statistics"],
        applyUrl: "https://www.inmobi.com/company/careers/",
        description: "Work on ad-tech algorithms that serve billions of requests. You will assist data scientists in model training and data preprocessing. Strong math/stats background preferred."
    },
    {
        id: 15,
        title: "Associate Consultant",
        company: "Oracle",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "8–10 LPA",
        source: "Oracle Careers",
        postedDaysAgo: 5,
        skills: ["SQL", "PL/SQL", "Oracle Database", "Java"],
        applyUrl: "https://www.oracle.com/corporate/careers/",
        description: "Join Oracle Financial Services Consulting. You will work on implementing and customizing Oracle banking products for global clients. Training on Oracle stack provided."
    },
    {
        id: 16,
        title: "Android Developer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "18–25 LPA",
        source: "LinkedIn",
        postedDaysAgo: 3,
        skills: ["Kotlin", "Android SDK", "Jetpack Compose", "MVVM"],
        applyUrl: "https://paytm.com/careers/",
        description: "Build the future of payments. We are looking for experienced Android developers who can build secure and fast financial applications. Experience with UPI integration is a plus."
    },
    {
        id: 17,
        title: "Cloud Support Associate",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Rotational Shifts",
        experience: "0-1 Years",
        salaryRange: "12–14 LPA",
        source: "Amazon Jobs",
        postedDaysAgo: 1,
        skills: ["Linux", "Networking", "AWS Basics", "Troubleshooting"],
        applyUrl: "https://www.amazon.jobs/en/",
        description: "Help AWS customers troubleshoot technical issues. You should have strong fundamentals in OS, Networking, and Databases. Great entry point into the cloud ecosystem."
    },
    {
        id: 18,
        title: "Frontend Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "12–27 LPA",
        source: "Juspay Careers",
        postedDaysAgo: 0,
        skills: ["PureScript", "Haskell", "React", "Functional Programming"],
        applyUrl: "https://juspay.in/careers",
        description: "Juspay is famous for its engineering culture. We use functional programming (PureScript/Haskell) on the frontend. We are looking for problem solvers who love coding at a deep level."
    },
    {
        id: 19,
        title: "Analyst",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "6–8 LPA",
        source: "Naukri",
        postedDaysAgo: 6,
        skills: ["Excel", "Tableau", "Power BI", "SQL"],
        applyUrl: "https://www2.deloitte.com/ui/en/careers/careers.html",
        description: "Join our Risk Advisory practice. You will analyze business processes and data to identify risks. Good analytical mind and proficiency in Excel/PowerBI needed."
    },
    {
        id: 20,
        title: "Golang Developer",
        company: "Gojek",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5 Years",
        salaryRange: "25–35 LPA",
        source: "LinkedIn",
        postedDaysAgo: 2,
        skills: ["Go", "Microservices", "gRPC", "Kubernetes"],
        applyUrl: "https://www.gojek.io/careers/",
        description: "Work on the Super App of Southeast Asia. We need Go experts to build high-throughput microservices. You will work on systems handling millions of orders."
    },

    // 21-30: Mix of roles
    {
        id: 21,
        title: "Java Developer",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "5–8 LPA",
        source: "Naukri",
        postedDaysAgo: 3,
        skills: ["Java 8", "Spring Boot", "Hibernate", "REST"],
        applyUrl: "https://www.capgemini.com/careers/",
        description: "Capgemini is hiring Java developers for its Financial Services unit. 2+ years of experience in Spring Boot is mandatory. Good exposure to Agile methodologies required."
    },
    {
        id: 22,
        title: "Software Engineer",
        company: "Microsoft",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "40–50 LPA",
        source: "Microsoft Careers",
        postedDaysAgo: 1,
        skills: ["C#", "Azure", "Algorithms", ".NET"],
        applyUrl: "https://careers.microsoft.com/",
        description: "Join the Azure India team. We deal with cloud scale problems. Looking for fresh graduates with exceptional problem-solving skills and strong CS fundamentals."
    },
    {
        id: 23,
        title: "UI Engineer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "18–25 LPA",
        source: "LinkedIn",
        postedDaysAgo: 4,
        skills: ["React", "TypeScript", "Performance", "CSS Modules"],
        applyUrl: "https://about.dream11.com/careers",
        description: "Build the interface for India's biggest fantasy sports platform. You should care deeply about render performance and smooth animations. React expertise is a must."
    },
    {
        id: 24,
        title: "Data Engineer",
        company: "Uber",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "30–45 LPA",
        source: "Uber Careers",
        postedDaysAgo: 2,
        skills: ["Spark", "Hadoop", "Python", "SQL"],
        applyUrl: "https://www.uber.com/us/en/careers/",
        description: "Uber's data platform team handles petabytes of data. We need engineers who can build scalable data pipelines. Experience with big data technologies like Spark is critical."
    },
    {
        id: 25,
        title: "Intern - Software",
        company: "Cisco",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹60k/month",
        source: "Jobs at Cisco",
        postedDaysAgo: 5,
        skills: ["Networking", "C/C++", "Python", "Linux"],
        applyUrl: "https://jobs.cisco.com/",
        description: "Cisco is looking for interns for its networking software group. You will work on router/switch operating systems. Strong C programming skills required."
    },
    {
        id: 26,
        title: "PHP Developer",
        company: "Lenskart",
        location: "Delhi NCR",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "8–12 LPA",
        source: "Naukri",
        postedDaysAgo: 2,
        skills: ["PHP", "Laravel", "MySQL", "JavaScript"],
        applyUrl: "https://hiring.lenskart.com/",
        description: "Maintain and enhance the Lenskart e-commerce backend. Experience with Laravel framework and optimized MySQL queries is important. Fast-paced startup environment."
    },
    {
        id: 27,
        title: "Test Automation Engineer",
        company: "Cognizant",
        location: "Chennai",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "9–14 LPA",
        source: "Cognizant Careers",
        postedDaysAgo: 4,
        skills: ["Java", "Selenium", "Cucumber", "Jenkins"],
        applyUrl: "https://careers.cognizant.com/",
        description: "Senior QA role for a US healthcare client. You must be able to design automation frameworks from scratch using Selenium. Experience with BDD (Cucumber) is preferred."
    },
    {
        id: 28,
        title: "Business Analyst",
        company: "Fractal",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1 Years",
        salaryRange: "7–10 LPA",
        source: "Fractal Careers",
        postedDaysAgo: 1,
        skills: ["Analytics", "Communication", "SQL", "Visualization"],
        applyUrl: "https://fractal.ai/careers/",
        description: "Bridge the gap between data science teams and business stakeholders. You need to translate business problems into data requirements. Good storytelling skills with data required."
    },
    {
        id: 29,
        title: "iOS Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "15–22 LPA",
        source: "LinkedIn",
        postedDaysAgo: 3,
        skills: ["Swift", "iOS SDK", "UIKit", "Xcode"],
        applyUrl: "https://www.urbancompany.com/careers",
        description: "Work on the partner app for Urban Company. We need iOS developers who understand mobile architecture and memory management. Swift proficiency is non-negotiable."
    },
    {
        id: 30,
        title: "Security Analyst",
        company: "Palo Alto Networks",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "14–20 LPA",
        source: "Indeed",
        postedDaysAgo: 5,
        skills: ["Network Security", "Firewalls", "Python", "Cybersecurity"],
        applyUrl: "https://jobs.paloaltonetworks.com/",
        description: "Monitor and analyze security threats. You will work with our advanced firewall products. Background in networking and security protocols is essential."
    },

    // 31-40: More diversity
    {
        id: 31,
        title: "SAP Consultant",
        company: "IBM",
        location: "Kolkata",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "10–15 LPA",
        source: "IBM Careers",
        postedDaysAgo: 2,
        skills: ["SAP SD", "ABAP", "ERP", "Consulting"],
        applyUrl: "https://www.ibm.com/careers",
        description: "Looking for SAP SD functional consultants. You should have done at least 2 end-to-end implementations. Good client-facing skills required."
    },
    {
        id: 32,
        title: "Frontend Intern",
        company: "CleverTap",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹25k/month",
        source: "LinkedIn",
        postedDaysAgo: 1,
        skills: ["HTML", "CSS", "JavaScript", "React Basic"],
        applyUrl: "https://clevertap.com/careers/",
        description: "Internship opportunity for frontend enthusiasts. You will work on our dashboard UI components. Mentorship provided by senior engineers."
    },
    {
        id: 33,
        title: "Site Reliability Engineer",
        company: "LinkedIn",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "35–50 LPA",
        source: "LinkedIn",
        postedDaysAgo: 0,
        skills: ["Linux", "Python/Go", "Automation", "Troubleshooting"],
        applyUrl: "https://www.linkedin.com/company/linkedin/jobs/",
        description: "Keep LinkedIn running. We look for engineers who hate manual tasks and automate everything. Deep Linux internals knowledge is required."
    },
    {
        id: 34,
        title: "Ruby on Rails Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "18–26 LPA",
        source: "Meesho Careers",
        postedDaysAgo: 3,
        skills: ["Ruby", "Rails", "PostgreSQL", "Redis"],
        applyUrl: "https://www.meesho.io/jobs",
        description: "Scale India's largest social commerce platform. We use RoR extensively. Looking for devs who can write clean, efficient Ruby code."
    },
    {
        id: 35,
        title: "Graduate Engineer Trainee",
        company: "Honeywell",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "6–8 LPA",
        source: "Naukri",
        postedDaysAgo: 4,
        skills: ["Embedded C", "Microcontrollers", "RTOS", "Electronics"],
        applyUrl: "https://careers.honeywell.com/",
        description: "Career starter for Electronics/CS engineers. You will work on building automation and aerospace controls. Strong basics in C and embedded systems needed."
    },
    {
        id: 36,
        title: "React Developer",
        company: "MakeMyTrip",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "14–20 LPA",
        source: "LinkedIn",
        postedDaysAgo: 2,
        skills: ["React", "Redux", "PWA", "Web Performance"],
        applyUrl: "https://careers.makemytrip.com/",
        description: "Build the travel app used by millions. Focus on performance and PWA features. Experience with optimizing loading times and rendering is crucial."
    },
    {
        id: 37,
        title: "Technical Writer",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Remote",
        experience: "3-5 Years",
        salaryRange: "12–18 LPA",
        source: "Salesforce Careers",
        postedDaysAgo: 5,
        skills: ["Documentation", "API Docs", "Markdown", "English"],
        applyUrl: "https://www.salesforce.com/company/careers/",
        description: "Create developer documentation for Salesforce APIs. You need to understand code and explain it simply. Samples of previous work required."
    },
    {
        id: 38,
        title: "Marketing Analyst",
        company: "Myntra",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "10–15 LPA",
        source: "Naukri",
        postedDaysAgo: 1,
        skills: ["SQL", "Excel", "Google Analytics", "Marketing"],
        applyUrl: "https://careers.myntra.com/",
        description: "Analyze marketing campaign performance for Myntra's fashion sales. You will work with the growth team to optimize spend. Analytical mindset is key."
    },
    {
        id: 39,
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3 Years",
        salaryRange: "20–40 LPA",
        source: "CryptoJobs",
        postedDaysAgo: 2,
        skills: ["Solidity", "Ethereum", "Smart Contracts", "Web3.js"],
        applyUrl: "https://polygon.technology/careers",
        description: "Build on the leading Ethereum scaling solution. We need Solidity developers who understand gas optimization and security. Remote-first culture."
    },
    {
        id: 40,
        title: "Node.js Developer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "12–18 LPA",
        source: "Dunzo Careers",
        postedDaysAgo: 3,
        skills: ["Node.js", "Express", "MongoDB", "AWS"],
        applyUrl: "https://www.dunzo.com/careers",
        description: "Power quick commerce in India. We need backend engineers proficient in Node.js. You will work on order dispatch and tracking systems."
    },

    // 41-50: More roles
    {
        id: 41,
        title: "Technical Support Engineer",
        company: "Dell",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "5–7 LPA",
        source: "Dell Careers",
        postedDaysAgo: 1,
        skills: ["Hardware", "Windows", "Networking", "Customer Service"],
        applyUrl: "https://jobs.dell.com/",
        description: "Provide technical support for Dell enterprise products. Good troubleshooting skills and command over English are required. Shift work involved."
    },
    {
        id: 42,
        title: "Data Scientist",
        company: "Walmart Global Tech",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "28–40 LPA",
        source: "LinkedIn",
        postedDaysAgo: 4,
        skills: ["Machine Learning", "Python", "Big Data", "Statistics"],
        applyUrl: "https://careers.walmart.com/",
        description: "Solve retail problems at scale. Optimization of supply chain and inventory using ML. Advanced degree in Math/Stats/CS preferred."
    },
    {
        id: 43,
        title: "Junior Java Developer",
        company: "Mindtree",
        location: "Bhubaneswar",
        mode: "Onsite",
        experience: "0-1 Years",
        salaryRange: "4–6 LPA",
        source: "Naukri",
        postedDaysAgo: 2,
        skills: ["Java", "SQL", "HTML", "CSS"],
        applyUrl: "https://www.mindtree.com/careers",
        description: "Entry level developer role for campus graduates. You will be trained on full stack Java development. Logical reasoning aptitude test is part of the process."
    },
    {
        id: 44,
        title: "Product Manager",
        company: "Unacademy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "25–35 LPA",
        source: "LinkedIn",
        postedDaysAgo: 5,
        skills: ["Product Strategy", "UX", "Agile", "Analytics"],
        applyUrl: "https://unacademy.com/careers",
        description: "Lead product initiatives for our test prep vertical. You need to understand student psychology and build features that improve learning outcomes."
    },
    {
        id: 45,
        title: "Cyber Security Analyst",
        company: "HCL Tech",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "6–9 LPA",
        source: "Naukri",
        postedDaysAgo: 3,
        skills: ["SOC", "SIEM", "Incident Response", "Networks"],
        applyUrl: "https://www.hcltech.com/careers",
        description: "Work in our Security Operations Center (SOC). Monitor alerts and respond to incidents. CEH or similar certification is valued."
    },
    {
        id: 46,
        title: "Flutter Developer",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "15–25 LPA",
        source: "Zerodha Careers",
        postedDaysAgo: 2,
        skills: ["Flutter", "Dart", "Mobile", "State Management"],
        applyUrl: "https://zerodha.com/careers",
        description: "We are experimenting with Flutter for some of our internal tools. Looking for devs who understand mobile rendering pipeline. Minimalistic coding style preferred."
    },
    {
        id: 47,
        title: "Cloud Engineer",
        company: "Google",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "50–70 LPA",
        source: "Google Careers",
        postedDaysAgo: 1,
        skills: ["GCP", "Kubernetes", "Terraform", "Python"],
        applyUrl: "https://careers.google.com/",
        description: "Help customers migrate to Google Cloud. You will architect solutions on GCP. Deep understanding of infrastructure and networking required."
    },
    {
        id: 48,
        title: "Angular Developer",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "10–15 LPA",
        source: "Naukri",
        postedDaysAgo: 4,
        skills: ["Angular", "TypeScript", "RxJS", "HTML/CSS"],
        applyUrl: "https://careers.techmahindra.com/",
        description: "Senior Angular developer needed for a telecom client. You must be an expert in RxJS and state management. Long term contract."
    },
    {
        id: 49,
        title: "Intern - Designing",
        company: "Adobe",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹50k/month",
        source: "Adobe Careers",
        postedDaysAgo: 2,
        skills: ["Photoshop", "Illustrator", "Creative Cloud", "Design"],
        applyUrl: "https://www.adobe.com/careers.html",
        description: "Design internship at the company that makes design tools. You will work with the marketing design team. Portfolio is mandatory."
    },
    {
        id: 50,
        title: "Game Developer",
        company: "Moonfrog",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "12–20 LPA",
        source: "LinkedIn",
        postedDaysAgo: 3,
        skills: ["Unity", "C#", "Game Design", "3D Math"],
        applyUrl: "https://moonfroglabs.com/careers/",
        description: "Work on casual games played by millions like Ludo Club. Unity 3D experience is required. Passion for gaming is a must."
    },

    // 51-60: Final mix
    {
        id: 51,
        title: "Application Support",
        company: "JPMorgan Chase",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "10–14 LPA",
        source: "JPMC Careers",
        postedDaysAgo: 1,
        skills: ["Unix", "SQL", "Monitoring", "ITIL"],
        applyUrl: "https://careers.jpmorgan.com/",
        description: "Support critical banking applications. You need to debug issues in production environments. Shift work and on-call rotation involved."
    },
    {
        id: 52,
        title: "Junior Data Engineer",
        company: "Mu Sigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "5–7 LPA",
        source: "Naukri",
        postedDaysAgo: 4,
        skills: ["Python", "SQL", "ETL", "Data Warehousing"],
        applyUrl: "https://www.mu-sigma.com/careers",
        description: "Start your data engineering journey. You will learn to build data pipelines. Intense training program involved."
    },
    {
        id: 53,
        title: "Content Writer (Tech)",
        company: "GeeksforGeeks",
        location: "Noida",
        mode: "Remote",
        experience: "0-1 Years",
        salaryRange: "4–6 LPA",
        source: "GeeksforGeeks Careers",
        postedDaysAgo: 2,
        skills: ["Writing", "DSA", "C++", "Explaining"],
        applyUrl: "https://practice.geeksforgeeks.org/careers",
        description: "Write articles on Data Structures and Algorithms. You must have solved 500+ problems on LeetCode/GFG. Help others learn coding."
    },
    {
        id: 54,
        title: "IT Recruiter",
        company: "Randstad",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "4–7 LPA",
        source: "Naukri",
        postedDaysAgo: 3,
        skills: ["Sourcing", "Screening", "LinkedIn Premium", "Hiring"],
        applyUrl: "https://www.randstad.in/careers/",
        description: "Source candidates for tech roles. You need to understand technical terminologies. Commission based incentives available."
    },
    {
        id: 55,
        title: "Salesforce Developer",
        company: "PwC",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5 Years",
        salaryRange: "12–18 LPA",
        source: "PwC Careers",
        postedDaysAgo: 1,
        skills: ["Apex", "Visualforce", "LWC", "Salesforce Cloud"],
        applyUrl: "https://www.pwc.in/careers.html",
        description: "Salesforce implementation for enterprise clients. LWC (Lightning Web Components) experience is mandatory. Certifications preferred."
    },
    {
        id: 56,
        title: "Manual Tester",
        company: "Tata Elxsi",
        location: "Trivandrum",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "5–8 LPA",
        source: "Naukri",
        postedDaysAgo: 5,
        skills: ["Testing", "Automotive", "Embedded", "JIRA"],
        applyUrl: "https://www.tataelxsi.com/careers",
        description: "Test automotive infotainment systems. Domain knowledge of automotive electronics is helpful. Attention to detail is critical."
    },
    {
        id: 57,
        title: "React Developer",
        company: "Cars24",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "14–20 LPA",
        source: "LinkedIn",
        postedDaysAgo: 2,
        skills: ["React", "Redux", "JavaScript", "HTML/CSS"],
        applyUrl: "https://www.cars24.com/careers",
        description: "Build the seller and buyer dashboards. Fast paced environment. We need devs who can ship features quickly with good quality."
    },
    {
        id: 58,
        title: "Network Engineer",
        company: "Airtel",
        location: "Delhi",
        mode: "Onsite",
        experience: "1-3 Years",
        salaryRange: "6–9 LPA",
        source: "Airtel Careers",
        postedDaysAgo: 4,
        skills: ["CCNA", "Routing", "Switching", "Telecom"],
        applyUrl: "https://www.airtel.in/careers",
        description: "Maintain network infrastructure for Airtel business. CCNA certification is mandatory. Willingness to work in shifts."
    },
    {
        id: 59,
        title: "Graphic Designer",
        company: "BookMyShow",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3 Years",
        salaryRange: "6–10 LPA",
        source: "LinkedIn",
        postedDaysAgo: 3,
        skills: ["Photoshop", "Illustrator", "Social Media", "Creativity"],
        applyUrl: "https://in.bookmyshow.com/careers",
        description: "Create visuals for movie releases and events. You will work with the social media team. Strong portfolio of creative ads required."
    },
    {
        id: 60,
        title: "AI Engineer",
        company: "Ola Electric",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5 Years",
        salaryRange: "30–45 LPA",
        source: "Ola Careers",
        postedDaysAgo: 1,
        skills: ["Computer Vision", "Deep Learning", "PyTorch", "C++"],
        applyUrl: "https://olaelectric.com/careers",
        description: "Work on autonomous driving tech for scooters and cars. Computer vision expertise is required. Experience with edge deployment is a plus."
    }
];
